# https://taskfile.dev

version: '3'

vars:
  EXENAME: distributed-rate-limiter.exe

tasks:
  build:
    cmds:
      - go build -o bin/{{.EXENAME}}
    silent: true

  run:
    deps: [build]
    cmds:
      - ./bin/{{.EXENAME}}
